{% set name = "scanpy" %}
{% set version = "1.9.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8cf5a4f1246e9dc5486d0ae9ac4950dc6fb5fa92c247cb571f96ff8e72145df

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scanpy = scanpy.cli:console_main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - anndata >=0.7.4
    - numpy >=1.17
    - matplotlib-base >=3.6
    - pandas >=1.1.1, !=2.1.2
    - scipy >=1.4
    - seaborn !=0.13.0
    - h5py >=3
    - tqdm
    - scikit-learn >=0.24
    - statsmodels >=0.11
    - patsy
    - networkx >=2.3
    - natsort
    - joblib
    - numba >=0.41
    - umap-learn >=0.3.10
    - packaging
    - session-info
    - get-annotations

test:
  imports:
    - scanpy
  # commands:
  #   - scanpy  # TODO: re-enable for 1.10.0
  requires:
    - pip
  commands:
    # - pip check  # https://github.com/conda-forge/tbb-feedstock/issues/119
    - python -c 'import importlib.metadata as im; print(im.version("scanpy"))'

about:
  home: https://scanpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    It includes preprocessing, visualization, clustering, trajectory inference and differential expression testing.
    The Python-based implementation efficiently deals with datasets of more than one million cells.
  doc_url: https://scanpy.readthedocs.io/
  dev_url: https://github.com/theislab/scanpy/

extra:
  recipe-maintainers:
    - flying-sheep
    - ivirshup
