{% set name = "scanpy" %}
{% set version = "1.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a9194d94985dee41d914fc9438f0b502dfacf54796d0501e06a5978d709c7f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scanpy = scanpy.cli:console_main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - anndata >=0.8
    - numpy >=1.23
    - matplotlib-base >=3.6
    - pandas >=1.5
    - scipy >=1.8
    - seaborn >=0.13
    - h5py >=3.1
    - tqdm
    - scikit-learn >=0.24
    - statsmodels >=0.13
    - patsy
    - networkx >=2.7
    - natsort
    - joblib
    - numba >=0.56
    - umap-learn >=0.5.1
    - pynndescent >=0.5
    - packaging >=21.3
    - session-info
    - legacy-api-wrap >=1.4
    - get-annotations

test:
  imports:
    - scanpy
  # commands:
  #   - scanpy  # TODO: re-enable for 1.10.0
  requires:
    - pip
  commands:
    # - pip check  # https://github.com/conda-forge/tbb-feedstock/issues/119
    - python -c 'import importlib.metadata as im; print(im.version("scanpy"))'

about:
  home: https://scverse.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    It includes preprocessing, visualization, clustering, trajectory inference and differential expression testing.
    The Python-based implementation efficiently deals with datasets of more than one million cells.
  doc_url: https://scanpy.readthedocs.io/
  dev_url: https://github.com/scverse/scanpy/

extra:
  recipe-maintainers:
    - flying-sheep
    - ivirshup
