{% set name = "scanpy" %}
{% set version = "1.9.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14957604d251c665d42a8fe55b51b6d19867c3e987054b12e65c762d13664463

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scanpy = scanpy.cli:console_main

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core
    - setuptools_scm
    - tomli
  run:
    - python >=3.8
    - anndata >=0.7.4
    - numpy >=1.17
    - matplotlib-base >=3.4
    - pandas >=1
    - scipy >=1.4
    - seaborn
    - h5py >=3
    - tqdm
    - scikit-learn >=0.24
    - statsmodels >=0.11
    - patsy
    - networkx >=2.3
    - natsort
    - joblib
    - numba >=0.41
    - umap-learn >=0.3.10
    - packaging
    - session-info
    - importlib_metadata

test:
  imports:
    - scanpy
  # commands:
  #   - scanpy  # TODO: re-enable for 1.10.0
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://scanpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    It includes preprocessing, visualization, clustering, trajectory inference and differential expression testing.
    The Python-based implementation efficiently deals with datasets of more than one million cells.
  doc_url: https://scanpy.readthedocs.io/
  dev_url: https://github.com/theislab/scanpy/

extra:
  recipe-maintainers:
    - flying-sheep
    - ivirshup
