{% set name = "scanpy" %}
{% set version = "1.12.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b87a5b1413ab33b69691df69c2084ff4ea8b389728e1542b22145825f88b5037

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scanpy = scanpy.cli:console_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - anndata >=0.10.8
    - fast-array-utils >=1.4
    - h5py >=3.11
    - joblib
    - matplotlib-base >=3.10
    - natsort
    - networkx >=2.8.8
    - numba >=0.60
    - numpy >=2
    - packaging >=25
    - pandas >=2.3
    - patsy
    - pynndescent >=0.5.13
    - scikit-learn >=1.6
    - scipy >=1.13
    - scverse-misc >=0.0.6
    - seaborn >=0.13.2
    - session-info2
    - statsmodels >=0.14.5
    - tqdm
    - typing-extensions
    - umap-learn >=0.5.12

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - scanpy
  commands:
    # - pip check  # https://github.com/conda-forge/tbb-feedstock/issues/119
    - python -c 'import importlib.metadata as im; print(im.version("scanpy"))'

about:
  home: https://scverse.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    It includes preprocessing, visualization, clustering, trajectory inference and differential expression testing.
    The Python-based implementation efficiently deals with datasets of more than one million cells.
  doc_url: https://scanpy.readthedocs.io/
  dev_url: https://github.com/scverse/scanpy/

extra:
  recipe-maintainers:
    - ilan-gold
    - jdblischak
    - flying-sheep
    - ivirshup
