{% set name = "scanpy" %}
{% set version = "1.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a88692f631d80f1b6a91d660a443d9534876173a0de236f25397ee396c2cace

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scanpy = scanpy.cli:console_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - anndata >=0.8
    - numpy >=1.24
    - matplotlib-base >=3.7
    - pandas >=1.5
    - scipy >=1.8
    - seaborn >=0.13
    - h5py >=3.7
    - tqdm
    - scikit-learn >=1.1,<1.6
    - statsmodels >=0.13
    - patsy !=1.0.0
    - networkx >=2.7
    - natsort
    - joblib
    - numba >=0.57
    - umap-learn >=0.5.1
    - pynndescent >=0.5
    - packaging >=21.3
    - session-info2
    - legacy-api-wrap >=1.4
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - scanpy
  commands:
    # - pip check  # https://github.com/conda-forge/tbb-feedstock/issues/119
    - python -c 'import importlib.metadata as im; print(im.version("scanpy"))'

about:
  home: https://scverse.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    It includes preprocessing, visualization, clustering, trajectory inference and differential expression testing.
    The Python-based implementation efficiently deals with datasets of more than one million cells.
  doc_url: https://scanpy.readthedocs.io/
  dev_url: https://github.com/scverse/scanpy/

extra:
  recipe-maintainers:
    - jdblischak
    - flying-sheep
    - ivirshup
